variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: 'trust'

stages:
  - test
  - release

services:
  - postgres:latest@sha256:3962158596daaef3682838cc8eb0e719ad1ce520f88e34596ce8d5de1b6330a1

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.4.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-gitlab-release@0.4.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-to-pypi@0.4.0

test:
  stage: test
  image: "registry.gitlab.com/thelabnyc/python:${IMAGE}"
  script:
    - uv sync --all-extras
    - uv run tox
  coverage: '/^TOTAL.+?(\d+\%)$/'
  parallel:
    matrix:
      - IMAGE: py312
        TOX_SKIP_ENV: "^(?!py312-)"
      - IMAGE: py313
        TOX_SKIP_ENV: "^(?!py313-)"
